import os
import json
import time
import random
from pathlib import Path

import chromadb
from dotenv import load_dotenv
from google import genai
from pydantic import BaseModel, Field


# ============================================================
# CONFIGURATION
# ============================================================

load_dotenv()

# Gemini client
client = genai.Client(
    api_key=os.getenv("GEMINI_API_KEY")
)

PRIMARY_MODEL = "gemini-3.8-flash"
FALLBACK_MODEL = "gemini-3.6-flash"

# ChromaDB client
chroma_client = chromadb.PersistentClient(
    path="./chroma_db"
)

# Existing course collection
collection = chroma_client.get_collection(
    name="data_science_course"
)


# ============================================================
# STRUCTURED OUTPUT MODELS
# ============================================================

class ConceptIdentification(BaseModel):
    """
    Identifies the broad topic and specific concept
    related to the student's question.
    """

    topic: str = Field(
        description="The broad Data Science topic."
    )

    concept: str = Field(
        description="The specific concept being asked about."
    )


class TutorResponse(BaseModel):
    """
    Structured response generated by Gemini.
    """

    topic: str = Field(
        description="The broad Data Science topic this question belongs to."
    )

    concept: str = Field(
        description="The specific concept being taught."
    )

    lesson: str = Field(
        description="The lesson explaining the concept simply."
    )

    quiz_question: str = Field(
        description="One short question testing the student's understanding."
    )

    expected_answer: str = Field(
        description="The correct answer to the quiz question."
    )

    quiz_explanation: str = Field(
        description="Why the expected answer is correct."
    )


class PracticeQuestion(BaseModel):
    """
    Structured practice question generated by Gemini.
    """

    question: str = Field(
        description="One practice question about the concept."
    )

    expected_answer: str = Field(
        description="The correct answer to the practice question."
    )

    explanation: str = Field(
        description="Why the expected answer is correct."
    )


class Evaluation(BaseModel):
    """
    Structured evaluation of the student's answer.
    """

    correct: bool = Field(
        description="Whether the student's answer is correct."
    )

    feedback: str = Field(
        description="Short and encouraging feedback for the student."
    )


class IntentDetection(BaseModel):
    """
    Identifies what the student wants to do.
    """

    intent: str = Field(
        description="The student's intent: teach, practice, or progress."
    )

    concept: str = Field(
        description="The Data Science concept involved. Use an empty string if not applicable."
    )


# ============================================================
# RELIABLE GEMINI GENERATION
# ============================================================

def generate_with_retry(
    prompt,
    response_schema,
    max_retries=3
):
    """
    Reliable Gemini generation.

    Strategy:

    Primary model
        ↓
    Retry temporary errors
        ↓
    If still unavailable
        ↓
    Fallback model
        ↓
    Retry fallback
    """

    models = [
        PRIMARY_MODEL,
        FALLBACK_MODEL
    ]

    for model_index, model in enumerate(models):

        for attempt in range(max_retries):

            try:

                print(
                    f"\n🤖 Using {model} "
                    f"(attempt {attempt + 1}/{max_retries})"
                )

                response = client.models.generate_content(
                    model=model,
                    contents=prompt,
                    config={
                        "response_mime_type": "application/json",
                        "response_schema": response_schema,
                    },
                )

                return response.parsed

            except Exception as e:

                error_text = str(e)

                # ------------------------------------------------
                # Temporary errors
                # ------------------------------------------------

                is_temporary_error = (
                    "503" in error_text
                    or "UNAVAILABLE" in error_text
                    or "500" in error_text
                    or "INTERNAL" in error_text
                    or "504" in error_text
                    or "DEADLINE_EXCEEDED" in error_text
                )

                # ------------------------------------------------
                # Do not retry permanent errors
                # ------------------------------------------------

                if not is_temporary_error:
                    raise

                # ------------------------------------------------
                # Last attempt for current model
                # ------------------------------------------------

                if attempt == max_retries - 1:

                    print(
                        f"\n⚠️ {model} is unavailable "
                        f"after {max_retries} attempts."
                    )

                    break

                # ------------------------------------------------
                # Exponential backoff + jitter
                # ------------------------------------------------

                base_delay = 2 ** attempt

                jitter = random.uniform(
                    0,
                    1
                )

                wait_time = base_delay + jitter

                print(
                    f"⚠️ Temporary Gemini error."
                    f" Retrying in {wait_time:.1f} seconds..."
                )

                time.sleep(wait_time)

        # --------------------------------------------------------
        # Move to fallback model
        # --------------------------------------------------------

        if model_index < len(models) - 1:

            print(
                f"\n🔄 Switching from "
                f"{model} → {models[model_index + 1]}"
            )

    raise RuntimeError(
        "Gemini is temporarily unavailable on both "
        "the primary and fallback models."
    )


# ============================================================
# STUDENT MEMORY
# ============================================================

PROGRESS_FILE = Path("progress.json")


def load_progress():
    """
    Load the student's learning progress from disk.
    """

    if not PROGRESS_FILE.exists():
        return {}

    with open(
        PROGRESS_FILE,
        "r",
        encoding="utf-8"
    ) as file:

        return json.load(file)


def save_progress(progress):
    """
    Save the student's learning progress to disk.
    """

    with open(
        PROGRESS_FILE,
        "w",
        encoding="utf-8"
    ) as file:

        json.dump(
            progress,
            file,
            indent=4
        )


def get_concept_history(topic, concept):
    """
    Read the student's previous learning history
    for a specific topic and concept.
    """

    progress = load_progress()

    if topic not in progress:
        return None

    if concept not in progress[topic]:
        return None

    return progress[topic][concept]


def calculate_mastery(topic, concept):
    """
    Calculate the student's mastery percentage
    for a specific concept.
    """

    history = get_concept_history(
        topic,
        concept
    )

    if history is None:
        return 0.0

    attempts = history["attempts"]

    if attempts == 0:
        return 0.0

    correct = history["correct"]

    mastery = correct / attempts

    return mastery


def get_learning_state(mastery):
    """
    Convert mastery score into a simple learning state.
    """

    if mastery < 0.5:
        return "weak"

    elif mastery < 0.8:
        return "learning"

    else:
        return "strong"


def get_progress_report():
    """
    Generate a learning progress report
    from the student's saved memory.
    """

    progress = load_progress()

    if not progress:

        print(
            "\n📊 No learning progress yet."
        )

        return

    print("\n" + "=" * 60)
    print("📊 YOUR DATA SCIENCE PROGRESS")
    print("=" * 60)

    total_concepts = 0
    strong_concepts = 0
    learning_concepts = 0
    weak_concepts = 0

    for topic, concepts in progress.items():

        print(f"\n📚 {topic}")
        print("-" * 60)

        for concept, data in concepts.items():

            total_concepts += 1

            attempts = data["attempts"]
            correct = data["correct"]

            if attempts == 0:
                mastery = 0
            else:
                mastery = correct / attempts

            state = get_learning_state(mastery)

            if state == "strong":

                strong_concepts += 1
                icon = "🟢"

            elif state == "learning":

                learning_concepts += 1
                icon = "🟡"

            else:

                weak_concepts += 1
                icon = "🔴"

            print(
                f"{icon} {concept:<25} "
                f"{mastery * 100:>5.0f}% "
                f"({correct}/{attempts}) "
                f"[{state}]"
            )

    print("\n" + "-" * 60)

    print(f"Total concepts : {total_concepts}")
    print(f"🟢 Strong      : {strong_concepts}")
    print(f"🟡 Learning    : {learning_concepts}")
    print(f"🔴 Weak        : {weak_concepts}")


def record_progress(
    tutor_response,
    student_answer,
    evaluation
):
    """
    Save the student's learning progress based on
    topic and concept rather than the exact question.
    """

    progress = load_progress()

    topic = tutor_response.topic
    concept = tutor_response.concept

    # --------------------------------------------------------
    # Create topic if it doesn't exist
    # --------------------------------------------------------

    if topic not in progress:
        progress[topic] = {}

    # --------------------------------------------------------
    # Create concept if it doesn't exist
    # --------------------------------------------------------

    if concept not in progress[topic]:

        progress[topic][concept] = {
            "attempts": 0,
            "correct": 0,
            "incorrect": 0,
            "history": []
        }

    concept_data = progress[topic][concept]

    # --------------------------------------------------------
    # Update counters
    # --------------------------------------------------------

    concept_data["attempts"] += 1

    if evaluation.correct:

        concept_data["correct"] += 1

    else:

        concept_data["incorrect"] += 1

    # --------------------------------------------------------
    # Save individual attempt
    # --------------------------------------------------------

    concept_data["history"].append({
        "question": tutor_response.quiz_question,
        "student_answer": student_answer,
        "correct": evaluation.correct
    })

    # --------------------------------------------------------
    # Save to file
    # --------------------------------------------------------

    save_progress(progress)


# ============================================================
# 1. RETRIEVE
# ============================================================

def retrieve(
    question,
    number_of_chunks=2
):
    """
    Convert the student's question into an embedding
    and retrieve the most relevant course material
    from ChromaDB.
    """

    result = client.models.embed_content(
        model="gemini-embedding-2",
        contents=question
    )

    question_embedding = result.embeddings[0].values

    results = collection.query(
        query_embeddings=[
            question_embedding
        ],
        n_results=number_of_chunks
    )

    return results["documents"][0]


# ============================================================
# 2. DETECT INTENT
# ============================================================

def detect_intent(question):
    """
    Understand what the student wants to do.

    Possible intents:
    - teach
    - practice
    - progress
    """

    prompt = f"""
You are the intent classifier for a Data Science tutor.

Understand what the student wants.

==================================================
STUDENT REQUEST
==================================================

{question}

==================================================
POSSIBLE INTENTS
==================================================

teach
    The student wants to learn or understand
    a Data Science concept.

practice
    The student wants questions or practice
    on a Data Science concept.

progress
    The student wants to see their learning
    progress, mastery, strengths, or weaknesses.

==================================================
RULES
==================================================

1. Return exactly one intent.

2. If the student asks to explain, learn,
   understand, or teach a concept:
   intent = "teach"

3. If the student asks for questions,
   practice, testing, or a quiz:
   intent = "practice"

4. If the student asks about their progress,
   mastery, performance, strengths, or weaknesses:
   intent = "progress"

5. Extract the concept if one is mentioned.

6. If no concept is relevant, return an
   empty string.

7. Do not invent a concept.
"""

    try:

        return generate_with_retry(
            prompt,
            IntentDetection
        )

    except Exception as e:

        print(
            "\n❌ Could not understand the request."
        )

        print("Reason:", e)

        return None


# ============================================================
# 3. IDENTIFY TOPIC + CONCEPT
# ============================================================

def identify_concept(
    question,
    retrieved_chunks
):
    """
    Identify the broad topic and specific concept
    before generating the lesson.

    This allows us to check the student's memory
    before teaching the concept.
    """

    context = "\n\n".join(
        retrieved_chunks
    )

    prompt = f"""
You are a Data Science tutor.

Your task is to identify the broad topic and
specific concept related to the student's question.

Use ONLY the course material provided below.

==================================================
COURSE MATERIAL
==================================================

{context}

==================================================
STUDENT QUESTION
==================================================

{question}

==================================================
RULES
==================================================

1. Identify a broad Data Science topic.

2. Identify the specific concept being asked about.

3. The topic should be broad.

Example:

Topic: Data Preprocessing
Concept: Public Data

NOT:

Topic: What is public data?
Concept: What is public data?

4. Do not invent concepts that are not supported
   by the course material.
"""

    try:

        return generate_with_retry(
            prompt,
            ConceptIdentification
        )

    except Exception as e:

        print(
            "\n❌ Could not identify the concept."
        )

        print("Reason:", e)

        return None


# ============================================================
# 4. GENERATE LESSON + QUIZ
# ============================================================

def generate_tutor_response(
    question,
    retrieved_chunks,
    concept_identification,
    concept_history,
    mastery,
    learning_state
):
    """
    Generate a structured lesson and quiz using:

    1. Course material
    2. Student question
    3. Identified concept
    4. Student's previous learning history
    5. Student mastery
    6. Learning state
    """

    context = "\n\n".join(
        retrieved_chunks
    )

    # --------------------------------------------------------
    # Convert memory into readable text
    # --------------------------------------------------------

    if concept_history is None:

        memory_context = """
The student has no previous learning history
for this concept.

Treat this as a new concept for the student.
"""

    else:

        memory_context = f"""
The student has studied this concept before.

Previous learning history:

{json.dumps(
    concept_history,
    indent=4
)}

Use this information to personalize the teaching.
"""

    prompt = f"""
You are a Data Science tutor.

Your job is to teach the student using ONLY the
course material provided below.

==================================================
COURSE MATERIAL
==================================================

{context}

==================================================
STUDENT QUESTION
==================================================

{question}

==================================================
IDENTIFIED TOPIC
==================================================

{concept_identification.topic}

==================================================
IDENTIFIED CONCEPT
==================================================

{concept_identification.concept}

==================================================
STUDENT MEMORY
==================================================

{memory_context}

==================================================
STUDENT MASTERY
==================================================

Mastery: {mastery * 100:.0f}%

Learning state: {learning_state}

==================================================
TEACHING RULES
==================================================

1. Teach ONLY using the provided course material.

2. Use the identified topic and concept.

3. Explain the concept as if teaching a 5-year-old.

4. Start with a very simple explanation.

5. Give a simple real-world analogy.

6. Then explain the technical meaning.

7. Give one simple example.

8. Create ONE short quiz question.

9. The quiz must test the concept being taught.

10. The quiz must be based ONLY on the course material.

11. Provide the correct expected answer.

12. Explain why the expected answer is correct.

13. Do not invent information outside the course material.

14. If the course material does not contain enough
    information, clearly say that the information
    was not found.

15. Keep the explanation beginner-friendly.

==================================================
PERSONALIZATION RULES
==================================================

If the student has previous history:

- Use it to understand their previous performance.
- Do not repeat exactly the same quiz question.
- If they previously answered correctly, you may
  make the explanation or quiz slightly more challenging.
- If they previously answered incorrectly, explain
  the concept more carefully and use another analogy.
- Do not assume mastery from a single correct answer.
- Do not invent knowledge about the student.

The student's memory is context, not course material.
Course material is always the source of truth.

==================================================
ADAPTIVE TEACHING RULES
==================================================

If the learning state is "weak":

- Explain the concept more slowly.
- Use a very simple analogy.
- Focus on the fundamental idea.
- Create an easier quiz question.
- Do not assume the student understands the concept.

If the learning state is "learning":

- Give a normal beginner-friendly explanation.
- Use one analogy and one example.
- Create a moderate quiz question.
- Reinforce the important parts of the concept.

If the learning state is "strong":

- Keep the explanation concise.
- Avoid repeating everything from previous lessons.
- Give a slightly more challenging quiz question.
- Test whether the student can apply the concept.
- Do not assume complete mastery from the score alone.
"""

    try:

        return generate_with_retry(
            prompt,
            TutorResponse
        )

    except Exception as e:

        print(
            "\n❌ Gemini could not generate the lesson."
        )

        print("Reason:", e)

        return None


# ============================================================
# 5. GENERATE PRACTICE QUESTION
# ============================================================

def generate_practice_question(
    concept,
    retrieved_chunks,
    concept_history,
    mastery,
    learning_state
):
    """
    Generate one practice question based on:
    - Course material
    - Student memory
    - Student mastery
    - Learning state
    """

    context = "\n\n".join(
        retrieved_chunks
    )

    if concept_history is None:

        memory_context = (
            "The student has no previous history "
            "for this concept."
        )

    else:

        memory_context = json.dumps(
            concept_history,
            indent=4
        )

    prompt = f"""
You are a Data Science practice tutor.

Your job is to create ONE practice question
for the student.

==================================================
COURSE MATERIAL
==================================================

{context}

==================================================
CONCEPT
==================================================

{concept}

==================================================
STUDENT MEMORY
==================================================

{memory_context}

==================================================
STUDENT MASTERY
==================================================

Mastery: {mastery * 100:.0f}%

Learning state: {learning_state}

==================================================
RULES
==================================================

1. Use ONLY the provided course material.

2. Create exactly ONE question.

3. The question must test the concept:
   {concept}

4. Do not copy a previous question exactly.

5. If the learning state is "weak":
   create an easier question focused on
   fundamental understanding.

6. If the learning state is "learning":
   create a moderate question.

7. If the learning state is "strong":
   create a slightly more challenging question
   that tests application or understanding.

8. Provide the expected answer.

9. Provide a short explanation of why the
   expected answer is correct.

10. Do not introduce information that is not
    supported by the course material.
"""

    try:

        return generate_with_retry(
            prompt,
            PracticeQuestion
        )

    except Exception as e:

        print(
            "\n❌ Gemini could not generate "
            "the practice question."
        )

        print("Reason:", e)

        return None


# ============================================================
# 6. EVALUATE STUDENT ANSWER
# ============================================================

def evaluate_answer(
    tutor_response,
    student_answer
):
    """
    Dynamically evaluate the student's answer.

    There are NO hardcoded questions or answers.
    """

    prompt = f"""
You are a strict but fair Data Science tutor.

==================================================
QUIZ QUESTION
==================================================

{tutor_response.quiz_question}

==================================================
EXPECTED ANSWER
==================================================

{tutor_response.expected_answer}

==================================================
EXPECTED ANSWER EXPLANATION
==================================================

{tutor_response.quiz_explanation}

==================================================
STUDENT ANSWER
==================================================

{student_answer}

==================================================
EVALUATION RULES
==================================================

1. Judge the meaning of the student's answer,
   not the exact wording.

2. A short answer can be completely correct.

3. Minor spelling or grammar mistakes should
   not make an answer incorrect.

4. If the student's answer communicates the same
   concept as the expected answer, mark it correct.

5. If the student's answer contradicts the expected
   answer, mark it incorrect.

6. If the answer is missing an important part that
   changes the meaning, mark it incorrect.

7. Give short, clear and encouraging feedback.

8. Do not invent information that is not contained
   in the expected answer or its explanation.
"""

    try:

        return generate_with_retry(
            prompt,
            Evaluation
        )

    except Exception as e:

        print(
            "\n❌ Gemini could not evaluate the answer."
        )

        print("Reason:", e)

        return None


# ============================================================
# 7. PRACTICE
# ============================================================

def practice(concept):
    """
    Practice a specific Data Science concept.
    """

    # --------------------------------------------------------
    # STEP 1: RETRIEVE COURSE MATERIAL
    # --------------------------------------------------------

    retrieved_chunks = retrieve(
        concept
    )

    # --------------------------------------------------------
    # STEP 2: IDENTIFY TOPIC + CONCEPT
    # --------------------------------------------------------

    concept_identification = identify_concept(
        concept,
        retrieved_chunks
    )

    if concept_identification is None:
        return

    actual_topic = (
        concept_identification.topic
    )

    actual_concept = (
        concept_identification.concept
    )

    # --------------------------------------------------------
    # STEP 3: READ STUDENT MEMORY
    # --------------------------------------------------------

    concept_history = get_concept_history(
        actual_topic,
        actual_concept
    )

    # --------------------------------------------------------
    # STEP 4: CALCULATE MASTERY
    # --------------------------------------------------------

    mastery = calculate_mastery(
        actual_topic,
        actual_concept
    )

    learning_state = get_learning_state(
        mastery
    )

    # --------------------------------------------------------
    # STEP 5: DISPLAY STUDENT STATUS
    # --------------------------------------------------------

    print("\n" + "=" * 60)
    print("🧠 PRACTICE MODE")
    print("=" * 60)

    print("\nTopic:")
    print(actual_topic)

    print("\nConcept:")
    print(actual_concept)

    print(
        f"\n📊 Mastery: "
        f"{mastery * 100:.0f}%"
    )

    print(
        f"📚 Learning state: "
        f"{learning_state}"
    )

    # --------------------------------------------------------
    # STEP 6: GENERATE PRACTICE QUESTION
    # --------------------------------------------------------

    practice_question = generate_practice_question(
        actual_concept,
        retrieved_chunks,
        concept_history,
        mastery,
        learning_state
    )

    if practice_question is None:
        return

    # --------------------------------------------------------
    # STEP 7: DISPLAY QUESTION
    # --------------------------------------------------------

    print("\n" + "-" * 60)
    print("📝 PRACTICE QUESTION")
    print("-" * 60)

    print(
        practice_question.question
    )

    # --------------------------------------------------------
    # STEP 8: GET STUDENT ANSWER
    # --------------------------------------------------------

    student_answer = input(
        "\nYour answer: "
    )

    # --------------------------------------------------------
    # STEP 9: EVALUATE ANSWER
    # --------------------------------------------------------

    evaluation_prompt = f"""
You are a strict but fair Data Science tutor.

QUESTION:
{practice_question.question}

EXPECTED ANSWER:
{practice_question.expected_answer}

EXPECTED ANSWER EXPLANATION:
{practice_question.explanation}

STUDENT ANSWER:
{student_answer}

Evaluate the student's answer.

Rules:

1. Judge meaning, not exact wording.

2. Minor spelling or grammar mistakes
   should not make an answer incorrect.

3. If the student communicates the same
   meaning as the expected answer, mark
   it correct.

4. If the answer contradicts the expected
   answer, mark it incorrect.

5. Give short and encouraging feedback.

6. Do not introduce information outside
   the expected answer and explanation.
"""

    try:

        evaluation = generate_with_retry(
            evaluation_prompt,
            Evaluation
        )

    except Exception as e:

        print(
            "\n❌ Gemini could not evaluate "
            "the practice answer."
        )

        print("Reason:", e)

        return

    if evaluation is None:
        return

    # --------------------------------------------------------
    # STEP 10: SAVE PROGRESS
    # --------------------------------------------------------

    tutor_response = TutorResponse(
        topic=actual_topic,
        concept=actual_concept,
        lesson="",
        quiz_question=practice_question.question,
        expected_answer=practice_question.expected_answer,
        quiz_explanation=practice_question.explanation
    )

    record_progress(
        tutor_response,
        student_answer,
        evaluation
    )

    # --------------------------------------------------------
    # STEP 11: DISPLAY RESULT
    # --------------------------------------------------------

    print("\n" + "=" * 60)
    print("🎯 PRACTICE RESULT")
    print("=" * 60)

    if evaluation.correct:

        print("\n✅ CORRECT!")
        print(evaluation.feedback)

    else:

        print("\n❌ NOT QUITE")
        print(evaluation.feedback)

        print("\nCorrect answer:")
        print(
            practice_question.expected_answer
        )

        print("\nWhy:")
        print(
            practice_question.explanation
        )

    # --------------------------------------------------------
    # STEP 12: SHOW UPDATED MASTERY
    # --------------------------------------------------------

    new_mastery = calculate_mastery(
        actual_topic,
        actual_concept
    )

    new_state = get_learning_state(
        new_mastery
    )

    print("\n📊 UPDATED PROGRESS")

    print(
        f"Mastery: "
        f"{new_mastery * 100:.0f}%"
    )

    print(
        f"Learning state: "
        f"{new_state}"
    )


# ============================================================
# 8. TEACH
# ============================================================

def teach(question):
    """
    Complete RAG tutoring pipeline.
    """

    # --------------------------------------------------------
    # STEP 1: RETRIEVE COURSE MATERIAL
    # --------------------------------------------------------

    retrieved_chunks = retrieve(
        question
    )

    # --------------------------------------------------------
    # STEP 2: IDENTIFY TOPIC + CONCEPT
    # --------------------------------------------------------

    concept_identification = identify_concept(
        question,
        retrieved_chunks
    )

    if concept_identification is None:
        return

    # --------------------------------------------------------
    # STEP 3: READ STUDENT MEMORY
    # --------------------------------------------------------

    concept_history = get_concept_history(
        concept_identification.topic,
        concept_identification.concept
    )

    mastery = calculate_mastery(
        concept_identification.topic,
        concept_identification.concept
    )

    learning_state = get_learning_state(
        mastery
    )

    # --------------------------------------------------------
    # SHOW MEMORY STATUS
    # --------------------------------------------------------

    print("\n🧠 STUDENT MEMORY")

    if concept_history is None:

        print(
            "No previous history for this concept."
        )

    else:

        print(
            f"Previous attempts: "
            f"{concept_history['attempts']}"
        )

        print(
            f"Previous correct: "
            f"{concept_history['correct']}"
        )

        print(
            f"Previous incorrect: "
            f"{concept_history['incorrect']}"
        )

    print(
        f"\n📊 Mastery: "
        f"{mastery * 100:.0f}%"
    )

    print(
        f"📚 Learning state: "
        f"{learning_state}"
    )

    # --------------------------------------------------------
    # STEP 4: GENERATE PERSONALIZED LESSON + QUIZ
    # --------------------------------------------------------

    tutor = generate_tutor_response(
        question,
        retrieved_chunks,
        concept_identification,
        concept_history,
        mastery,
        learning_state
    )

    if tutor is None:
        return

    # --------------------------------------------------------
    # STEP 5: DISPLAY LESSON
    # --------------------------------------------------------

    print("\n" + "=" * 60)
    print("📚 YOUR DATA SCIENCE TUTOR")
    print("=" * 60)

    print("\nTopic:")
    print(tutor.topic)

    print("\nConcept:")
    print(tutor.concept)

    print("\n" + tutor.lesson)

    # --------------------------------------------------------
    # STEP 6: DISPLAY QUIZ
    # --------------------------------------------------------

    print("\n" + "-" * 60)
    print("🧠 QUICK CHECK")
    print("-" * 60)

    print(
        tutor.quiz_question
    )

    # --------------------------------------------------------
    # STEP 7: GET STUDENT ANSWER
    # --------------------------------------------------------

    student_answer = input(
        "\nYour answer: "
    )

    # --------------------------------------------------------
    # STEP 8: EVALUATE ANSWER
    # --------------------------------------------------------

    evaluation = evaluate_answer(
        tutor,
        student_answer
    )

    if evaluation is None:
        return

    # --------------------------------------------------------
    # STEP 9: SAVE PROGRESS
    # --------------------------------------------------------

    record_progress(
        tutor,
        student_answer,
        evaluation
    )

    # --------------------------------------------------------
    # STEP 10: DISPLAY FEEDBACK
    # --------------------------------------------------------

    print("\n" + "=" * 60)
    print("🎯 FEEDBACK")
    print("=" * 60)

    if evaluation.correct:

        print("\n✅ CORRECT!")
        print(
            evaluation.feedback
        )

    else:

        print("\n❌ NOT QUITE")
        print(
            evaluation.feedback
        )

        print("\nCorrect answer:")
        print(
            tutor.expected_answer
        )

        print("\nWhy:")
        print(
            tutor.quiz_explanation
        )


# ============================================================
# 9. AGENT
# ============================================================

def agent(question):
    """
    Main Agentic AI entry point.

    The agent:
    1. Understands the student's intention.
    2. Selects the appropriate capability.
    3. Executes it.
    """

    intent_result = detect_intent(
        question
    )

    if intent_result is None:
        return

    intent = intent_result.intent
    concept = intent_result.concept

    print("\n🤖 AGENT")
    print(
        f"Intent: {intent}"
    )

    if concept:

        print(
            f"Concept: {concept}"
        )

    # --------------------------------------------------------
    # TEACH
    # --------------------------------------------------------

    if intent == "teach":

        teach(question)

    # --------------------------------------------------------
    # PRACTICE
    # --------------------------------------------------------

    elif intent == "practice":

        if not concept:

            print(
                "\nPlease tell me which concept "
                "you want to practice."
            )

            return

        practice(
            concept
        )

    # --------------------------------------------------------
    # PROGRESS
    # --------------------------------------------------------

    elif intent == "progress":

        get_progress_report()

    else:

        print(
            "\nI couldn't determine what you want to do."
        )


# ============================================================
# MAIN PROGRAM
# ============================================================

if __name__ == "__main__":

    question = input(
        "\nAsk your Data Science Tutor: "
    )

    agent(question)